const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "221760263631"
const SESSION_ID = "PRABATH-MD~d6dTlATa#5i6Pcl3NldXMmpz8JeIxGUCrMpkWqjmtfEnsR_ZxDjI"

module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
