# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json into the container
COPY package*.json ./

# Install the app dependencies
RUN npm install

# Copy the rest of the application code into the container
COPY . .

# Expose the port the app will run on (if your app runs on port 3000)
EXPOSE 8000

# Define the command to run your app (assuming "npm start" is the correct start command)
CMD ["npm", "start"]
